/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/6.7.1/userguide/building_java_projects.html
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use JCenter for resolving dependencies.
    jcenter()
}

dependencies {

    testImplementation("org.junit.jupiter:junit-jupiter-api:5.6.2")
    testImplementation("org.junit.jupiter:junit-jupiter-params:5.6.2")

    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine")

    testImplementation("com.h2database:h2:1.4.200")

    testImplementation("org.assertj:assertj-core:3.19.0")
}

application {
    // Define the main class for the application.
    mainClass.set("de.dbubenheim.learning.App")
}

tasks.test {
    // Use junit platform for unit tests.
    useJUnitPlatform()
}
